@extends('layouts.app')
@section('title', 'Rault Film | Search')
@section('content')
    {{-- search wrapper --}}
    <div class="w-full h-auto min-h-screen  ">
        {{-- search input --}}
        <div class="w-full pl-10 lg:pl-20 pr-10 lg:pr-0">
            <div class="relative w-full lg:w-80 mt-10 bg-white drop-shadow-[0_0px_4px_rgba(0,0,0,0.25)]">
                <input type="search" id="searchInput"
                    class="block w-full p-8 lg:p-4 pl-12 lg:pl-10 text-2xl lg:text-sm text-black focus:outline-none "
                    placeholder="search..." required>
                <div class="absolute inset-y-0 left-0 flex items-center pl-3 pointer-events-none">
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="size-4">
                        <path fill-rule="evenodd"
                            d="M10.5 3.75a6.75 6.75 0 1 0 0 13.5 6.75 6.75 0 0 0 0-13.5ZM2.25 10.5a8.25 8.25 0 1 1 14.59 5.28l4.69 4.69a.75.75 0 1 1-1.06 1.06l-4.69-4.69A8.25 8.25 0 0 1 2.25 10.5Z"
                            clip-rule="evenodd" class="fill-black group-hover:fill-rault-500 duration-200 " />
                    </svg>
                </div>
            </div>
        </div>

        {{-- content section --}}
        <div class="w-auto pl-28 pr-10 pt-6 pb-10 grid grid-cols-3 lg:grid-cols-5 gap-5" id="dataWrapper">
            {{-- wait ajax --}}
        </div>
        {{-- DATA LOADER --}}
        <div class="w-full pl-28 pr-10 flex justify-center mb-5" id="autoLoad">
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid" width="54"
                height="54" style="shape-rendering: auto; display: block; background: rgb(255, 255, 255);"
                xmlns:xlink="http://www.w3.org/1999/xlink">
                <g>
                    <path style="transform:scale(0.8);transform-origin:50px 50px" stroke-linecap="butt"
                        d="M24.3 30C11.4 30 5 43.3 5 50s6.4 20 19.3 20c19.3 0 32.1-40 51.4-40 C88.6 30 95 43.3 95 50s-6.4 20-19.3 20C56.4 70 43.6 30 24.3 30z"
                        stroke-dasharray="42.76482137044271 42.76482137044271" stroke-width="8" stroke="#121212"
                        fill="none">
                        <animate values="0;256.58892822265625" keyTimes="0;1" dur="1s" repeatCount="indefinite"
                            attributeName="stroke-dashoffset"></animate>
                    </path>
                    <g></g>
                </g><!-- [ldio] generated by https://loading.io -->
            </svg>
        </div>

        {{-- ERROR NOTIFICATION --}}
        <div id="notification"
            class="min-w-[250px] p-4 bg-red-700 text-white text-center rounded-lg fixed z-index-10 top-0 right-0 mr-10 mt-5 drop-shadow-lg">
            <span id="notificationMessage"></span>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.7.1.min.js"
        integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>

    <script>
        let baseURL = "<?php echo $baseURL; ?>";
        let imageBaseURL = "<?php echo $imageBaseURL; ?>";
        let apiKey = "<?php echo $apiKey; ?>";
        let searchKeyWord = "";

        // Hide Loader 
        $("#autoLoad").hide();
        // Hide Notification 
        $("#notification").hide();

        $('#searchInput').keypress(function(event) {
            var key = event.which;
            if (key == 13) {
                searchKeyWord = $('#searchInput').val();
                if (searchKeyWord) {
                    search();
                }
                return false;
            }
        });

        function search() {
            $.ajax({
                    url: `${baseURL}/search/multi?page=1&api_key=${apiKey}&query=${searchKeyWord}`,
                    type: "get",
                    beforeSend: function() {
                        // Show Loader
                        $("#autoLoad").show();
                        //clear content
                        $("#dataWrapper").html("");
                    }
                })
                .done(function(response) {
                    console.log(response); 
                    $("#autoLoad").hide();

                    if (response.results) {
                        var htmlData = [];
                        response.results.forEach(item => {
                            if (item.media_type == 'movie' || item.media_type == 'tv') {
                                let searchTitle = "";
                                let originalDate = "";
                                let detailsURL = "";

                                if (item.media_type == 'movie') {
                                    detailsURL = `/movie/${item.id}`;
                                    originalDate = item.release_date;
                                    searchTitle = item.title;
                                } else {
                                    detailsURL = `/tv/${item.id}`;
                                    originalDate = item.first_air_date;
                                    searchTitle = item.name;
                                }

                                let date = new Date(originalDate);
                                let seachYear = date.getFullYear();
                                let searchImage = item.poster_path ?
                                    `${imageBaseURL}/w500/${item.poster_path}` : 'https://placehold.co/300x400';
                                let seachRating = item.vote_average * 10;
                                let searchVoter = item.vote_count;

                                htmlData.push(`<a href="${detailsURL}" class="group">
                    <div class="min-w-[232px] min-h-[428px] bg-white drop-shadow-[0_0px_8px_rgba(0,0,0,0.25)] 
                        group-hover:drop-shadow-[0_0px_8px_rgba(0,0,0,0.5)] rounded-[32px] p-5 flex flex-col mr-8 duration-100">
                        <div class="overflow-hidden rounded-[32px]">
                            <img class="w-full h-[300px] rounded-[32px] group-hover:scale-125 duration-200"
                                src="${searchImage}">
                        </div>
                        <span class="font-inter font-bold text-xl mt-4 line-clamp-1 group-hover:line-clamp-none">${searchTitle}</span>
                        <span class="font-inter text-sm mt-1">${seachYear}</span>
                        <div class="flex flex-row mt-1 items-center">
                            <svg class="w-6 h-6 text-gray-800 dark:text-white" aria-hidden="true"
                                xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="#38B6FF"
                                viewBox="0 0 24 24">
                                <path fill-rule="evenodd"
                                    d="M15.03 9.684h3.965c.322 0 .64.08.925.232.286.153.532.374.717.645a2.109 2.109 0 0 1 .242 1.883l-2.36 7.201c-.288.814-.48 1.355-1.884 1.355-2.072 0-4.276-.677-6.157-1.256-.472-.145-.924-.284-1.348-.404h-.115V9.478a25.485 25.485 0 0 0 4.238-5.514 1.8 1.8 0 0 1 .901-.83 1.74 1.74 0 0 1 1.21-.048c.396.13.736.397.96.757.225.36.32.788.269 1.211l-1.562 4.63Z" 
                                    clip-rule="evenodd" />
                            </svg>
                            <span class="font-inter text-sm ml-1 mr-4">${seachRating}%</span>
                            <svg class="w-6 h-6 text-gray-800 dark:text-white" aria-hidden="true"
                                xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="#38B6FF"
                                viewBox="0 0 24 24 ">
                                <path fill-rule="evenodd"
                                    d="M12 6a3.5 3.5 0 1 0 0 7 3.5 3.5 0 0 0 0-7Zm-1.5 8a4 4 0 0 0-4 4 2 2 0 0 0 2 2h7a2 2 0 0 0 2-2 4 4 0 0 0-4-4h-3Zm6.82-3.096a5.51 5.51 0 0 0-2.797-6.293 3.5 3.5 0 1 1 2.796 6.292ZM19.5 18h.5a2 2 0 0 0 2-2 4 4 0 0 0-4-4h-1.1a5.503 5.503 0 0 1-.471.762A5.998 5.998 0 0 1 19.5 18ZM4 7.5a3.5 3.5 0 0 1 5.477-2.889 5.5 5.5 0 0 0-2.796 6.293A3.501 3.501 0 0 1 4 7.5ZM7.1 12H6a4 4 0 0 0-4 4 2 2 0 0 0 2 2h.5a5.998 5.998 0 0 1 3.071-5.238A5.505 5.505 0 0 1 7.1 12Z" 
                                    clip-rule="evenodd" />
                            </svg>
                            <span class="font-inter text-sm ml-1 mr-4">${searchVoter}</span>
                        </div>
                    </div>
                </a>`);
                            }
                        });

                        $("#dataWrapper").append(htmlData.join(""));

                    }

                })
                .fail(function(jqXHR, ajaxOptions, thrownError) {
                    $("#autoLoad").hide();
                    // Show Notifications
                    $("#notificationMessage").text("Error Boskuhh!");
                    $("#notification").show();
                    // Set Timeout
                    setTimeout(function() {
                        $("#notification").hide();
                    }, 3000);
                });
        }
    </script>
@endsection
